version: '3.8'
services:
    postgres:
        build:
          context: .
          dockerfile: Dockerfile.Postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432

    redis:
        image: redis:6.0.6-alpine
        command: redis-server
        ports:
        - 6379:6379

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: Plants
        volumes:
            - .scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    # autograding is gonna run this
    rentit-test:
        image: rentit:1.0
        network_mode: host
        command: sh -c "cd test && go test -run='' -v"
        depends_on: 
            - rentit-actual
    
    # a weird workaround for autograding, when using "docker-compose run" directly on this
    # ports don't seem to be accessible, but they are accessible if this is a dependency
    # or maybe I am stupid
    rentit-actual:
        image: rentit:1.0
        ports:
            - 8080:8080
            - 8081:8081
            - 10001:10001
        command: sh -c "go run main.go"
        depends_on: 
            - redis
            - postgres
            - mongo
    
    rentit:
        image: rentit:1.0
        depends_on: 
            - rentit-actual
