version: '3.8'
services:
    postgres:
        build:
          context: .
          dockerfile: Dockerfile.Postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
    redis:
        image: redis:6.0.6-alpine
        command: redis-server
        ports:
        - 6379:6379

    repository-service-test:
        image: rentit:1.0
        command: sh -c "sleep 1 && cd test && go test -run='Repository' -v"

    grpc-test:
        image: rentit:1.0
        command: sh -c "sleep 1 && cd test && go test -run='Grpc' -v"

    rentit:
        image: rentit:1.0
        ports:
        - 8080:8080
        - 10001:10001
        command: sh -c "go run main.go"
            
    # grpc:
    #     image: rentit:1.0
    #     # network_mode: host
    #     ports:
    #     - 10001:10001
    #     command: sh -c "go run pkg/transport/grpc/server/main/grpcServer.go"
